### ISSUE TITLE
jquery-ui@1.13.1 vulnerabilities 

### ISSUE THREAD

**Issue by netzarbeiter** [contao-components/jquery-ui#1]
[latest non vulnerable version 1.13.2 ](https://security.snyk.io/package/npm/jquery-ui/1.13.1)

**Comment by leofeyer** [comment]
We are not affected by the vulnerability (see https://github.com/contao-components/jquery-ui/compare/1.13.1...1.13.2), because we only use the accordion widget of the jQuery UI library. I have still updated the component.

**Comment by netzarbeiter** [comment]
Thank you, Leo
